package com.replaymod.replaystudio.tools;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.LinkedHashMap;

public class DatapackGenerator {
    public static class Result {
        public final File packDir;
        public final File functionFile;
        public final int commandCount;
        public Result(File packDir, File functionFile, int commandCount) {
            this.packDir = packDir;
            this.functionFile = functionFile;
            this.commandCount = commandCount;
        }
    }

    public static Result generate(File jsonFile, File outputRoot, String packName, String namespace, String functionName) throws IOException {
        JsonObject root = new JsonParser().parse(new InputStreamReader(new java.io.FileInputStream(jsonFile), StandardCharsets.UTF_8)).getAsJsonObject();
        JsonObject inventory = root.getAsJsonObject("inventory");
        List<String> commands = new ArrayList<>();
        for (Map.Entry<String, JsonElement> e : inventory.entrySet()) {
            String slotId = e.getKey();
            JsonObject item = e.getValue().getAsJsonObject();
            String mcSlot = mapSlot(Integer.parseInt(slotId));
            if (mcSlot == null) {
                continue;
            }
            String name = item.has("name") ? item.get("name").getAsString() : "minecraft:air";
            int count = item.has("count") ? item.get("count").getAsInt() : 1;
            String nbt = item.has("nbt") ? item.get("nbt").getAsString() : "";
            String itemArg = name + nbt;
            String cmd = "item replace entity @s " + mcSlot + " with " + itemArg + " " + count;
            commands.add(cmd);
        }
        File packDir = new File(outputRoot, packName);
        File functionDir = new File(new File(new File(packDir, "data"), namespace), "functions");
        functionDir.mkdirs();
        File functionFile = new File(functionDir, functionName + ".mcfunction");
        try (FileWriter w = new FileWriter(functionFile)) {
            for (String cmd : commands) {
                w.write(cmd);
                w.write("\n");
            }
        }
        File packMcmeta = new File(packDir, "pack.mcmeta");
        Map<String, Object> mcmeta = new LinkedHashMap<>();
        Map<String, Object> pack = new LinkedHashMap<>();
        pack.put("pack_format", 15);
        pack.put("description", packName + " generated by MCPR Inventory Tool");
        mcmeta.put("pack", pack);
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        try (FileWriter w = new FileWriter(packMcmeta)) {
            gson.toJson(mcmeta, w);
        }
        return new Result(packDir, functionFile, commands.size());
    }

    private static String mapSlot(int pid) {
        if (pid == 5) return "armor.head";
        if (pid == 6) return "armor.chest";
        if (pid == 7) return "armor.legs";
        if (pid == 8) return "armor.feet";
        if (pid >= 9 && pid <= 35) return "inventory." + (pid - 9);
        if (pid >= 36 && pid <= 44) return "hotbar." + (pid - 36);
        if (pid == 45) return "weapon.offhand";
        return null;
    }
}
